#!/bin/bash

########################################################################
# Color Parameters
########################################################################
NO_COLOR='\033[0m'
RED='\033[0;31m'
GREEN='\033[0;32m'
ORANGE='\033[0;33m'
BLUE='\033[0;34m'
PURPLE='\033[0;35m'
CYAN='\033[0;36m'
LIGHTGRAY='\033[0;37m'
DARKGRAY='\033[1;30m'
LIGHTRED='\033[1;31m'
LIGHTGREEN='\033[1;32m'
YELLOW='\033[1;33m'
LIGHTBLUE='\033[1;34m'
LIGHTPURPLE='\033[1;35m'
LIGHTCYAN='\033[1;36m'
WHITE='\033[1;37m'

########################################################################
# TA Setup Parameters
########################################################################
LAB="hw2"
ID=$(whoami)  # Get current user ID
TOP_FOLDER="${LAB}_${ID}"
DIRS=("signal" "buffer" "fifo")  # Target directories
SOURCE_DIRS=("../01_SOURCE/SC_SIGNAL" "../01_SOURCE/SC_BUFFER" "../01_SOURCE/SC_FIFO")
ARCHIVE_NAME="${LAB}_${ID}.tar.gz"

########################################################################
# (0) Create Top Folder
########################################################################
if [ -d "$TOP_FOLDER" ]; then
    echo -e "${YELLOW}[Info] Top folder $TOP_FOLDER exists. Removing old folder and creating a new one.${NO_COLOR}"
    rm -rf "$TOP_FOLDER"
fi
mkdir "$TOP_FOLDER"
echo -e "${GREEN}[Info] Top folder created: $TOP_FOLDER${NO_COLOR}"

########################################################################
# (1) Create Target Directories and Copy Files
########################################################################
for i in "${!DIRS[@]}"; do
    dir="${DIRS[$i]}"
    src_dir="${SOURCE_DIRS[$i]}"
    TARGET_DIR="$TOP_FOLDER/$dir"
    if [ -d "$TARGET_DIR" ]; then
        echo -e "${YELLOW}[Info] Directory $TARGET_DIR exists. Removing old directory and creating a new one.${NO_COLOR}"
        rm -rf "$TARGET_DIR"
    fi
    mkdir "$TARGET_DIR"
    echo -e "${GREEN}[Info] Directory created: $TARGET_DIR${NO_COLOR}"

    ########################################################################
    # (2) Copy all .h, .hpp and .cpp files and rename them
    ########################################################################
    for file in "$src_dir"/*; do
        if [ -f "$file" ]; then  # Ensure it's a valid file
            ext="${file##*.}"
            filename="${file%.*}"
            base_filename=$(basename "$filename")

            if [[ "$ext" == "h" || "$ext" == "hpp" || "$ext" == "cpp" ]]; then
                cp "$file" "$TARGET_DIR/${base_filename}_${dir}_${ID}.$ext"
                echo -e "${CYAN}[Info] Copied: $file -> $TARGET_DIR/${base_filename}_${dir}_${ID}.$ext${NO_COLOR}"
            fi
        fi
    done
done

########################################################################
# (3) Create tar archive
########################################################################
echo -e "${YELLOW}[Info] Creating tar archive: $ARCHIVE_NAME${NO_COLOR}"
tar -zcvf "$ARCHIVE_NAME" "$TOP_FOLDER"/
if [ $? -eq 0 ]; then
    echo -e "${GREEN}[Success] $ARCHIVE_NAME created successfully.${NO_COLOR}"
else
    echo -e "${RED}[Error] Failed to create $ARCHIVE_NAME.${NO_COLOR}"
    exit 1
fi